baseURL: https://dotsplayground.com/
theme: pure
title: Yet another gamedev blog
defaultContentLanguage: en  # en/zh/...
footnoteReturnLinkContents: ↩
hasCJKLanguage: true
paginate: 7
enableEmoji: true
googleAnalytics: ""      # UA-XXXXXXXX-X 
permalinks:
  posts: /:year/:month/:filename/

taxonomies:
    category : categories
    tag : tags
    series : series
outputFormats:          # use for search. recommend not to modify 
  SearchIndex:
    mediaType: "application/json"
    baseName: "searchindex"
    isPlainText: true
    notAlternative: true
    
outputs:
    home: ["HTML","RSS","SearchIndex"]  # recommend not to modify
# sitemap
sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.5

menu:
  main:
    - identifier: home
      name: Home
      title: Home 
      url: /
      weight: 1

    - identifier: series
      name: Series
      title: Series
      url: /series
      weight: 2

    - identifier: archives
      name: Archives
      title: Archives
      url: /posts
      weight: 3

    - identifier: categories
      name: Categories
      title: Categories
      url: /categories
      weight: 4

    - identifier: tags
      name: Tags
      title: Tags
      url: /tags
      weight: 5

    - identifier: about
      name: About
      title: About
      url: /about
      weight: 6


params:
  since: 2019
  dateFormatToUse: "2006-01-02"
  enablePostCopyright: false
  # Enable/Disable menu icons
  menuIcons:
    enable: true
    home: icon-home-fill
    archives: icon-archives-fill
    categories: icon-folder
    tags: icon-tags
    repository: icon-project
    books: icon-book-fill
    links: icon-friendship
    about: icon-users
    series: icon-project

  # profile
  profile:
    enabled: true # Whether to show profile bar
    avatar: avatar.png
    gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
    author: DOTS Playground
    authors: [[Simon,Simon Renger,"http://simonrenger.de"],[Niels,Niels van Steeg,"https://github.com/Nvs2000"],[Menno,Menno Markus,"https://github.com/MennoMarkus"],[Marjolein,Marjolein Kaal,"https://github.com/MarjoleinKaal"],[Maiko,Maiko Steeman,"https://github.com/FireFlyForLife"],[Jesse,Jesse Roffel,"https://github.com/jesseroffel"],[Jonah,Jonah Rutten,"https://github.com/JonahRutten"],[Pepijn,Pepijn Averink,"https://github.com/PepijnAverink"],[Robin,Robin,"https://github.com/RobinACS"]]
    author_title: Year 3 Students Gamedevs
    author_description: Good Good Study, Day Day Up~
    location: Breda University of Applied Sciences
    follow: https://github.com/Eothaun/DOTS-Playground/
    # Social Links
    social:
      links:
        github: [[Marjolein,"https://github.com/MarjoleinKaal"],[Maiko,"https://github.com/FireFlyForLife"],[Menno,"https://github.com/MennoMarkus"], [Niels,"https://github.com/Nvs2000"],[Jesse,"https://github.com/jesseroffel"],[Jonah,"https://github.com/JonahRutten"],[Pepijn,"https://github.com/PepijnAverink"],[Robin,"https://github.com/RobinACS"],[Simon,"https://github.com/simonrenger"]]
        # weibo: http://weibo.com/{yourid}
        # twitter: https://twitter.com/
        # facebook: /
        rss: /index.xml
      link_tooltip: false # enable the social link tooltip, options: true, false
  # Site
  site:
    logo:
      enabled: false
      width: 40
      height: 40
      url: favicon.ico
    title: Yet another game dev blog # 页面title
    favicon: favicon.ico
    board: <p>Write programs that do one thing and do it well. Write programs to work together — McIlroy Unix philosophy <br><br>Write systems that do one thing and do it well. Write systems to work together — DOD adoption</p> # 公告牌

  # Share
  # weibo,qq,qzone,wechat,tencent,douban,diandian,facebook,twitter,google,linkedin
  share:
    enable: true # 是否启用分享
    sites: facebook,twitter,linkedin # PC端显示的分享图标
    mobile_sites: facebook,twitter,linkedin # 移动端显示的分享图标

  # Comment
  comment:
    type:  # type disqus/gitalk/valine 启用哪种评论系统
    disqus: your_disqus_name # enter disqus shortname here
    gitalk: # gitalk. https://gitalk.github.io/
      owner: #必须. GitHub repository 所有者，可以是个人或者组织。
      admin: #必须. GitHub repository 的所有者和合作者 (对这个 repository 有写权限的用户)。
      repo:  #必须. GitHub repository.
      ClientID: #必须. GitHub Application Client ID.
      ClientSecret: #必须. GitHub Application Client Secret.
    valine: # Valine. https://valine.js.org
      appid: # your leancloud application appid
      appkey: # your leancloud application appkey
      notify: # mail notifier , https://github.com/xCss/Valine/wiki
      verify: # Verification code
      placeholder: enjoy~ # comment box placeholder
      avatar: mm # gravatar style
      meta: nick,mail # custom comment header
      pageSize: 10 # pagination size
      visitor: false # Article reading statistic https://valine.js.org/visitor.html

  # Donate
  donate:
    enable: false
    # 微信打赏
    wechatpay:
      qrcode: donate/wechatpayimg.png
      title: 微信支付
    # 支付宝打赏
    alipay:
      qrcode: donate/alipayimg.png
      title: 支付宝

  # PV
  pv:
    busuanzi:
      enable: false # 不蒜子统计
    leancloud:
      enable: false # leancloud统计
      app_id: # leancloud <AppID>
      app_key: # leancloud <AppKey>

  # wordcount
  postCount:
    enable: true
    wordcount: true # 文章字数统计
    min2read: true # read time 阅读时长预计

  # config
  config:
    skin: # theme color default is white. other type [theme-black,theme-blue,theme-green,theme-purple]
    layout: main-center # 布局方式 main-left main-center main-right
    excerpt_link: Read More
    toc: true

  # Sidebar
  sidebar: right

  # Search
  search:
    enable: true # enable search. thanks for https://raw.githubusercontent.com/ppoffice/hexo-theme-icarus/master/source/js/insight.js

  # Sidebar only the following widgets. you can remove any you don't like it.
  widgets:
    - board
    - category
    - tag
    - recent_posts

